name: go-middleware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          go-version: [1.18.x]

      steps:
        - uses: actions/setup-go@v3
          with:
            go-version: ${{ matrix.go-version }}
        - uses: actions/checkout@v3
        - run: go build ./...
